### ISSUE TITLE
ng2-archwizard module can't import with "strict": true flag

### ISSUE THREAD

**Issue by PerumalJP** [madoar/angular-archwizard#66] opened 2017-10-16 11:31 UTC
Hi, 
Congrats for awesome component! I am facing issues when i update the latest version 2.0.0 and above. If i import ng2-archwizard module set with **"strict":true** in tsconfig.json. 
`import { ArchwizardModule } from 'ng2-archwizard';`
Error throws like
[ts] Could not find a declaration file for module 'ng2-archwizard'. '/mydir/node_modules/ng2-archwizard/index.js' implicitly has an 'any' type.

**Comment by madoar** [comment] 2017-10-17 07:50
I'll take a look at the code, to see where I'm using `any`. 
I'm not sure, but it may be possible that it's required, if this is the case this will be hard to fix.

**Comment by madoar** [comment] 2017-11-01 20:16
@PerumalJP sorry for my late feedback.
I had a little time today to experiment a bit with this.

Can you go to the `ng2-archwizard` folder inside your `node_modules` folder in your project and copy the `index.js` to `index.d.ts`?
After doing this your `ng2-archwizard` folder should contain both an `index.js` and an `index.d.ts` file with the same content, i.e. `export * from './dist';`.
Afterwards, can you please tell me if this solves the error messages?

**Comment by PerumalJP** [comment] 2017-11-03 06:39
I have tried that as you said, even it shows the same error message.

**Comment by madoar** [comment] 2017-11-03 09:34
@PerumalJP can you post your project, otherwise it's hard to find the source of the problem, especially because a new `index.d.ts` file fixes the issue for my test project?

**Comment by apawsey** [comment] 2017-12-28 22:52
Just to add, I had the same issue, and adding the index.d.ts file with the following content seems to resolve it (haven't actually got round to testing the whole app, but everything builds nicely)
```
declare module 'ng2-archwizard'
export * from './dist';
```

**Comment by madoar** [comment] 2017-12-30 12:00
@apawsey thanks for your help. Can you please try if your app still works with these changes?
If this is the case, do you want to open a new Pull Request?

**Comment by apawsey** [comment] 2018-01-08 17:07
Seems all good in my testing.  Will do a PR when I get a chance

**Comment by felipealbrecht** [comment] 2018-02-15 01:30
Please, can you included the fixes in the original package and release a new version?

**Comment by karmasakshi** [comment] 2018-03-14 19:21
Hi, the OP (@PerumalJP) and I work on the same project. I can confirm that your solution works. We just had to update the module name:

`/node_modules/ng2-archwizard/index.d.ts`:

`declare module 'ArchwizardModule'
export * from './dist';`

You may close this issue. Will this be a part of an upcoming release?

**Comment by madoar** [comment] 2018-03-16 15:15
@karmasakshi, @PerumalJP thank you for giving this a test.
I'm currently working on a new major version, i.e. version `3.0.0`.
This new version uses `ng-packagr` to build the library for production.
The problem here is, that I don't know if it the same solution can be used here.
Could you please give version `3.0.0` a test to see if the `declare module 'ArchwizardModule';` statement is still required?
Please be aware, that version `3.0.0` introduces some syntactical changes!

About your question:
If it is still required, and doesn't lead to other problems I'll include it in the next release (version `3.0.0`).

**Closed** 2018-09-28 14:45 UTC
Labels: enhancement
