### ISSUE TITLE
Navigation Bar weird class behaviour

### ISSUE THREAD

**Issue by guillaumegarcia13** [madoar/angular-archwizard#124] opened 2018-06-04 15:53 UTC
Hi,

I observed a weird behaviour when using optional steps in terms of how classes are applied to li nodes

## Optional non-last step 
Let's consider the following setup:
 1 -> 2 -> 3 (optional) -> 4

I am interested in this 3rd optional step.

### Symptoms
Here is an example of the rendered navigation bar when validating step by step:
![image](https://user-images.githubusercontent.com/2786038/40927263-9626dbd8-681e-11e8-9fe9-f4c5e338ad96.png)
  --> class is set to: **optional**
![image](https://user-images.githubusercontent.com/2786038/40927279-a1e28260-681e-11e8-833a-f8be08d73f9b.png)
  --> class is set to: **current**

### Expected
I would have expected to have both current AND optional so as to be able to achieve this display instead:
![image](https://user-images.githubusercontent.com/2786038/40927440-01929fd8-681f-11e8-8dcb-fd1bc3e0a1cf.png)

## Optional last step 
Let's consider the following setup:
 1 -> 2 -> 3 -> 4 (optional)

I am now interested in this 4th optional step.

### Symptoms
When reaching 3rd (now required) step, everything is fine
![image](https://user-images.githubusercontent.com/2786038/40927650-8961740c-681f-11e8-8a58-396aa2bf3ed3.png)
  --> class is set to: **optional**
But when the 4th step is entered
![image](https://user-images.githubusercontent.com/2786038/40927679-9fd0f2c6-681f-11e8-9e38-91eba6c15d8b.png)
  --> class is set to: **done**

Another issue is when going back to 3rd step, all steps have class 'done' although one would expect to have editing
![image](https://user-images.githubusercontent.com/2786038/40928498-eeea0e90-6821-11e8-8682-9e1a432b0e29.png)
  --> class of 3rd and 4th steps is : **done**

### Expected
Same as before, meaning this:
![image](https://user-images.githubusercontent.com/2786038/40927760-d65af6e8-681f-11e8-928c-f8788b49c3b3.png)

Any option other than completely remove the navigation bar and implement my own?

**Comment by madoar** [comment] 2018-06-05 08:53
Yes, this seems to be unintended behavior:

1) About the optional, non-last steps I agree, this behavior is totally wrong.
2) For the following question about an optional last step, I would like to know if you've used a "normal" last step, i.e. `aw-wizard-step` or a completion step, i.e. `aw-wizard-completion-step`?

   When using optional it's not really important which step it is (i.e. if it is the last step or a "normal" step). Therefore the "optional" issue here is the same one as for point (1)
3) About the done part, this should depend on the kind of last step you've chosen.

   If you've used a completion step, **all** steps of the wizard are marked as done.
4) About the editing part, I'm not really sure what the user does, and how the wizard should react.

About your options:
I'm currently low on time to work on the wizard.
Therefore I would appreciate it, if you could give it a try, to fix the issues.
It shouldn't be too much work, and it's a lot faster, than to implement your own wizard! :)

All issues should be located in https://github.com/madoar/angular-archwizard/blob/master/src/components/wizard-navigation-bar.component.ts
In this class you'll see a lot of `is...` methods (like `isCurrent` or `isDone`).
These methods are responsible for the decision, which css classes are added to a wizard step in the navigation bar.
So if you change these methods you should be able to solve the issues.

If you decide to fix the issues, it would be quite nice if you create a new PR with the solution, so that other users also get access to the bug fixes.

**Comment by guillaumegarcia13** [comment] 2018-06-05 10:34
@madoar 
> 2. For the following question about an optional last step, I would like to know if you've used a "normal" last step, i.e. aw-wizard-step or a completion step, i.e. aw-wizard-completion-step?

I did not, all steps are either normal or optional ones.
Is having both (optional AND completion) supported?

>3. About the done part, this should depend on the kind of last step you've chosen.
If you've used a completion step, all steps of the wizard are marked as done.

Well, considering the state of the overall wizard:
![image](https://user-images.githubusercontent.com/2786038/40970772-e61ed012-68bb-11e8-8445-02e9becad8fe.png)
the following scenario:
1 (completed) -> 2 (completed) -> 3 (completed) -> 4 (optional)
results in having everything set to 'done'.
![image](https://user-images.githubusercontent.com/2786038/40970900-3eaaa940-68bc-11e8-8b8f-dbd18ab222de.png)

> 4. About the editing part, I'm not really sure what the user does, and how the wizard should react.

Actually, it would make sense to have 'editing' class on 3rd step and 'done' on 4th step, right?

I'm modifying the files right now (first time I clone a dependency, set it as a local dependency 🎉).
I'll keep you posted!

**Comment by guillaumegarcia13** [comment] 2018-06-05 11:27
I now get what's troubling me with this 'optional' last step.
Consider this scenario : 
  1 -> 2 (optional) -> 3 (optional) -> 4 (optional)

On the first step, the user validates and goes to step 2.
But, as all remaining steps are optional, the entire wizard is consided 'completed' and steps are marked as 'done'.

I am unsure how to deal with this in antoher way but skipping all remaining steps certainly can be unsettling.

**Comment by madoar** [comment] 2018-06-05 12:39
The completion step has the purpose of showing the user that the wizard has been completed and he's now unable to change anything he entered in the wizard.

An example where such a step is useful is a registration form.
Normally a registration form contains multiple steps (pages), which ask the user for information.
After the user filled out all the information asked for in the steps he presses `confirm`.
The click leads the user to a completion step, which gives the user a summary of the entered information.
After entering the completion step the account has been created, i.e. a database call has been made etc., it is normally undesired, that a user goes back to a previous step and changes some information, like his username.

A possible solution, I can think of, is to use two different css classes for the completion:
- the first class symbolizes, that the step itself has been completed
- the second class symbolizes, that the whole wizard has been completed

An optional step, which has been skipped, would then only have the second class assigned, which symbolizes, that the whole wizard has been completed, but not the step itself.

What do you think?

**Comment by guillaumegarcia13** [comment] 2018-06-05 12:50
I very much like this idea of differentiating between 'completed' (as in 'the user completed this stemp') and 'done' (as in wizard is finished)

**Comment by madoar** [comment] 2018-06-12 20:14
This should depend on which wizard step component you use for the final step:
- if you use a normal `wizard-step` you will get the behavior you've described, i.e. the step can't be completed, because you can't leave it in a forwards direction.
- if you use a `completion-wizard-step` you'll get a different behavior.

   A completion step automatically sets itself as completed, when it's entered, see also https://github.com/madoar/angular-archwizard/blob/master/src/util/wizard-completion-step.interface.ts#L25

**Comment by madoar** [comment] 2018-11-01 15:48
I'm currently thinking about adding a fix for this issue to the next release (i.e. `4.0.0`).

As far as I know, the issue arises through two subissues: 
- the order of the css class definitions in the stylesheets
   For example, `current` is specified prior to `optional`, which would result in optional overriding the styles set by current, which seems reversed to me
- the fact, that some css classes are currently disjunct.
   For example:
      - `current` and `optional`
      - `current` and `done` (which are translated to `editing`)

Therefore, to solve this issue I believe both issues need to be fixed.
In addition, I think it is possible (and a good idea at the same time) to reduce the number of css classes for the wizard steps.
I think we can change the wizard to remove the following css classes:
- `editing`: this css class could be replaced by a combination of the css classes `current` and `done`
- `default`: this css class looks obsolete to me, because in my opinion it is the default behavior in case no css class is applied to a wizard step

@earshinov I would like to know your opinion about this?

**Comment by earshinov** [comment] 2018-12-24 13:44
@madoar , I am glad to be back. Let me add my comments point by point:

> the order of the css class definitions in the stylesheets

I agree, this needs to be fixed as soon as the new set of CSS classes is settled.

> the fact, that some css classes are currently disjunct.

I do not understand fully what you mean by 'disjunct' here, but to me the situation when an element gets exactly one of, let's say, 3 classes seems fine. For instance, the current scheme of `current|done|editing` is ok in this sense (_but bad in another, so I am in favor for its reconsideration_).

I see a special case of 2 disjunct classes. In this case only 1 class could be provided, and the user would target the second case with `:not(...)` CSS selector. This selector is well supported nowadays and already used in archwizard.

> In addition, I think it is possible (and a good idea at the same time) to reduce the number of css classes for the wizard steps.

Agree, we should fight redundancy, and keep the exact amount of CSS classes we need to cover all use cases.

> `editing`: this css class could be replaced by a combination of the css classes `current` and `done`

In this case, the condition for `done` should be changed like this:

    //return (wizardStep.completed && !wizardStep.selected) || this.wizardState.completed;
    return wizardStep.completed || this.wizardState.completed;

> `default`: this css class looks obsolete to me

Agree. For targeting required steps as opposed to optional, the user has an option to use `:not(.optional)`.

**Comment by earshinov** [comment] 2018-12-24 13:46
Here is a complete proposal for further discussion:

		/* current */
		//wizardStep.selected && !wizardStep.completed && !this.wizardState.completed;
		wizardStep.selected && !this.wizardState.completed;

		/* done */
		//(wizardStep.completed && !wizardStep.selected) || this.wizardState.completed;
		wizardStep.completed || this.wizardState.completed;

		/* optional */
		//wizardStep.optional && !wizardStep.completed && !wizardStep.selected && !this.wizardState.completed
		wizardStep.optional

		/* navigable */
		!wizardStep.selected && !this.wizardState.disableNavigationBar &&   this.navigationMode.isNavigable(this.wizardState.getIndexOfStep(wizardStep));

**Comment by madoar** [comment] 2018-12-24 13:55
Nice to hear that you're back!

>> the fact, that some css classes are currently disjunct.

> I do not understand fully what you mean by 'disjunct' here, but to me the situation when an element gets exactly one of, let's say, 3 classes seems fine. For instance, the current scheme of current|done|editing is ok in this sense (but bad in another, so I am in favor for its reconsideration).

With disjunct I mean, that the `current` css class replaces the `optional` and `done` css classes.
This leads to the reduction of "freedom" for the developer who maybe wants to add some css behavior exactly to the `current & optional` or `current & done` case.

**Comment by earshinov** [comment] 2018-12-24 13:57
Ah, thanks for clarification. Definitely a bad thing!

**Comment by earshinov** [comment] 2018-12-24 13:59
Demo time: https://stackblitz.com/edit/angular-archwizard-css-classes

The demo uses the current release of aw.

**Comment by madoar** [comment] 2018-12-24 14:08
I like your css class proposal.
It is much simpler and easier to understand too.

The next question is: what do we need to change on the css file side to support the new css class conditions visually?

**Comment by earshinov** [comment] 2018-12-24 14:12
> The next question is: what do we need to change on the css file side to support the new css class conditions visually?

Should not be much harder than a little CSS reorganization.

Let me bring up another subject first :-) It seems that everyone agreed that providing separate CSS classes for a completed step and a completed wizard is a good thing. If so, here is a modified proposal with a separate .completed class that will be added to each step once the whole wizard is completed:

		/* current */
		//wizardStep.selected && !wizardStep.completed && !this.wizardState.completed;
		wizardStep.selected

		/* done */
		//(wizardStep.completed && !wizardStep.selected) || this.wizardState.completed;
		wizardStep.completed

		/* optional */
		//wizardStep.optional && !wizardStep.completed && !wizardStep.selected && !this.wizardState.completed
		wizardStep.optional

		/* completed */
		this.wizardState.completed

What do you think of it?

**Comment by earshinov** [comment] 2018-12-24 17:48
OK, I think I'll prepare PR in the next few days.

**Comment by earshinov** [comment] 2018-12-24 17:51
I think I've found a bug, reproducible on the demo page:
https://angular-archwizard-css-classes.stackblitz.io/

Scenario:
1. In the wizard with the competion step, click though the steps until you reach the completion step.
2. Observe that indicators for previous steps react to hover, but clicking them does not cause navigation:

![previous step is hoverable but not clickable after visiting completion step](https://user-images.githubusercontent.com/52021/50404819-8e5a3280-07bd-11e9-8465-02a7cdec3730.png)

I suggest we deal with this bug separately / later. Shall I file a bug report?

**Comment by earshinov** [comment] 2018-12-24 18:44
Submitted PR https://github.com/madoar/angular-archwizard/pull/181.

You can either try it out locally by hooking it into angular-archwizard-demo, or use the demo page at https://stackblitz.com/edit/angular-archwizard-css-classes-pr.

Does it resolve all the problems we need to resolve? I mean, the CSS classes are now 'segregated', which resolves the [non-last optional step problem](https://github.com/madoar/angular-archwizard/issues/124#issue-329115606). However, about the last optional step problem I am not so sure.

**Comment by madoar** [comment] 2018-12-24 20:43
You're right this is a bug.
When the wizard has been completed the navigation bar shouldn't show previous steps as navigable.
Yes, please file a bug report.

**Comment by madoar** [comment] 2019-12-09 13:15
I think we can consider this issue as solved.
The only remaining part should be #181 which is tracked in its own issue.
If there is still something open I think we should open new issues for that as well.

**Closed by madoar** 2019-12-09 13:15 UTC
Labels: bug
