### ISSUE TITLE
Wizard not loading components for second time

### ISSUE THREAD

**Issue by DeveBj** [madoar/angular-archwizard#78] opened 2017-12-21 11:34 UTC
Am getting following error when calling the wizard component second time

**Console Error** 

```
ERROR Error: The default step index 2 is located after a non optional step
    at StrictNavigationMode.webpackJsonp.../../../../ng2-archwizard/dist/navigation/strict-navigation-mode.js.StrictNavigationMode.reset (vendor.bundle.js:68023)
    at WizardState.webpackJsonp.../../../../ng2-archwizard/dist/navigation/wizard-state.model.js.WizardState.initialize (vendor.bundle.js:68168)
    at WizardComponent.webpackJsonp.../../../../ng2-archwizard/dist/components/wizard.component.js.WizardComponent.ngAfterContentInit (vendor.bundle.js:66545)
    at callProviderLifecycles (vendor.bundle.js:147388)
    at callElementProvidersLifecycles (vendor.bundle.js:147369)
    at callLifecycleHooksChildrenFirst (vendor.bundle.js:147353)
    at checkAndUpdateView (vendor.bundle.js:148465)
    at callViewAction (vendor.bundle.js:148830)
    at execEmbeddedViewsAction (vendor.bundle.js:148788)
    at checkAndUpdateView (vendor.bundle.js:148463)
```

**Comment by madoar** [comment] 2017-12-21 13:12
I'm not sure what you mean by calling the wizard component a second time?
Could you add a short code example, that leads to the error? This would make it easier for me to help you solve your problem :)

**Comment by DeveBj** [comment] 2017-12-21 13:16
@madoar inside my wizard am having 5 menus when the 4th menu is clicked and when i Click nest and exit the wizard, after that am again invoking the wizard at that time nothing is displayed i means the menus, I think the wizard step tag is not initialised, am having a Lot of code so I think its quite not easy to post a Short code here, but this is my Scenario, can you at least throw some hints based on the console error posted in my questions

**Comment by DeveBj** [comment] 2017-12-22 06:43
@madoar  any idea ?..

**Comment by madoar** [comment] 2017-12-22 15:48
What do you mean with `menu`? Do you mean a context menu? A menu inside a sidebar/navbar or something entirely different? How exactly do you enter the wizard again? Do you use angular routing, or something different?

As a short term solution, to help you understand what exactly the wizard does, you can try changing the navigation mode to `free`, this should prevent the error from showing up. 
About the meaning of the error message:
The message tells you, that the wizard tries to reset the wizard to step 2 (which is the third step because it's 0 index based). During the reset process it discovers that one of the earlier steps, i.e. the first or second step, is a non optional step (i.e. it is not marked with `optional`). This leads to the error you're shown.

**Comment by DeveBj** [comment] 2018-01-09 10:43
@madoar  Sorry for the late reply, actually am having a side nav bar inside the wizard after clicking the specific menu and completing the wizard, let say am having 5 menus on the first click of 4th menu the wizard renders correctly once completing the wizard and again clicking the new button to creata new wizard am getting the above error, I have also user navigationMode but same error only am geting, please help me to resolve this

**Comment by madoar** [comment] 2018-01-16 20:17
I still don't fully understand your question.
As far as I understand you have a navbar inside your wizard.
But what exactly the user can do inside the navbar I don't understand.

It sounds a little bit like you're trying to create a nested wizard (through "creating a new wizard" via the menu inside the navbar), this may be the reason for the above error message, because it's possible then that both wizards share the same model (which is bad).

**Comment by kahovn** [comment] 2018-01-19 04:09
I have the same error
my problem: have 5 step in form, I want to display 3th step => how to do?
here my code: 
<wizard defaultStepIndex="2">
</wizard>
The error: The default step index 2 is located after a non optional step

Please advance!

**Comment by madoar** [comment] 2018-01-23 18:38
@kahovn sorry for my late answer.

The message suggests that you want to set the third step as the default step.
The problem is, that either the first or the second step is not marked as optional.
To fix the problem you can either mark both the first and second step as optional, or set the navigation mode of the wizard to `free`.

I don't see your code. Can you please check that it's inserted correctly inside your message?

**Comment by madoar** [comment] 2018-09-28 14:45
If this question is still relevant/open, feel free to open a new issue.

**Closed by madoar** 2018-09-28 14:45 UTC
Labels: question

**Comment by sagunpandey** [comment] 2019-03-26 21:08
> @kahovn sorry for my late answer.
> 
> The message suggests that you want to set the third step as the default step.
> The problem is, that either the first or the second step is not marked as optional.
> To fix the problem you can either mark both the first and second step as optional, or set the navigation mode of the wizard to `free`.
> 
> I don't see your code. Can you please check that it's inserted correctly inside your message?

For example, if we select index 2 as the default index, can we mark step 0 and 1 as done while initiating the wizard?
